on: push
name: make all
jobs:
  makeall:
    name: make all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: make all
        uses: docker://golang:latest
        with:
          entrypoint: bash
          args: -c "go get honnef.co/go/tools/cmd/staticcheck && go get golang.org/x/lint/golint && make fmt lint staticcheck vet install"
